SELECT *
FROM worksheet
;

SELECT *,
ROW_NUMBER () OVER
(PARTITION BY ROW_ID, ORDER_ID, ORDER_DATE,
SHIP_MODE, CUSTOMER_NAME, SEGMENT, COUNTRY, Product_ID, Sub_Category, Sales, Profit
) AS ROW_NUM
FROM worksheet
;
WITH WORKSHEET_CTE AS
(SELECT *,
ROW_NUMBER () OVER
(PARTITION BY ROW_ID, ORDER_ID, ORDER_DATE,
SHIP_MODE, CUSTOMER_NAME, SEGMENT, COUNTRY, Product_ID, Sub_Category, Sales, Profit
) AS ROW_NUM
FROM worksheet
)
SELECT* 
FROM WORKSHEET_CTE
WHERE ROW_NUM >1
;

SELECT DISTINCT(CUSTOMER_NAME), TRIM(CUSTOMER_NAME)
FROM worksheet
;

SELECT * 
FROM worksheet
;

SELECT ROUND(sum(SALES)), SUM(QUANTITY), ROUND(SUM(PROFIT))
FROM worksheet
;

SELECT SEGMENT, ROUND(SUM(SALES))
FROM worksheet
GROUP BY SEGMENT
;
SELECT PRODUCT_NAME, ROUND(SUM(SALES)), ROUND(SUM(PROFIT))
FROM WORKSHEET
GROUP BY PRODUCT_NAME
;
WITH TOP AS
(SELECT PRODUCT_NAME, ROUND(SUM(SALES)) AS SALES,
 ROUND(SUM(PROFIT)) AS PROFIT
FROM WORKSHEET
GROUP BY PRODUCT_NAME
)
SELECT * 
FROM TOP
ORDER BY SALES DESC
LIMIT 10
;

SELECT PRODUCT_NAME, ROUND(SUM(SALES)), ROUND(SUM(PROFIT))
FROM WORKSHEET
GROUP BY PRODUCT_NAME
;
WITH TOP_PROFIT AS 
(SELECT PRODUCT_NAME, ROUND(SUM(SALES)) AS SALES, ROUND(SUM(PROFIT)) AS PROFIT
FROM WORKSHEET
GROUP BY PRODUCT_NAME
)
SELECT *
FROM TOP_PROFIT
ORDER BY PROFIT ASC
LIMIT 10
;